import { useMemo, useRef, useState } from 'react';
import catalog from '../data/customizer/catalog.generated.json';
import metadataFile from '../data/customizer/v3-overrides.json';
import { assetUrl, sampleLogoUrls } from '../lib/customizer/assets';

type View = 'front' | 'back' | 'left' | 'right';
type Panel = 'home' | 'placement' | 'items' | 'notes' | 'products';
type Item = { id: number; colourId: string; sizeId: string; quantity: number };
type Placement = { src: string; source: string; cx: number; cy: number; size: number; angle: number };
type Design = { view: View; activeItem: number; items: Item[]; placements: Partial<Record<View, Placement>>; notes: string };
const order: View[] = ['front', 'back', 'left', 'right'];
const products = catalog.products as any[];
const metadata = (metadataFile as any).products as Record<string, any>;
const title = (v: View) => ({ front: 'Front Logo', back: 'Back Logo', left: 'Left Sleeve', right: 'Right Sleeve' })[v];
const makeDesign = (product: any): Design => { const colour = metadata[product.id]?.defaultColour ?? product.colours[0].id; return { view: 'front', activeItem: 1, items: [{ id: 1, colourId: colour, sizeId: '', quantity: 1 }], placements: {}, notes: '' }; };

export default function ProductCustomizerV3() {
  const dialog = useRef<HTMLDialogElement>(null); const drag = useRef<{ view: View; box: DOMRect; offsetX: number; offsetY: number }>(); const nextItem = useRef(2);
  const defaultProduct = products.find(p => p.id === 'shirts/SET1') ?? products[0];
  const [productId, setProductId] = useState(defaultProduct.id); const [designs, setDesigns] = useState<Record<string, Design>>(() => Object.fromEntries(products.map(p => [p.id, makeDesign(p)])));
  const [panel, setPanel] = useState<Panel>('home'); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(''); const [undo, setUndo] = useState<Partial<Record<View, Placement>> | null>(null);
  const product = products.find(p => p.id === productId)!; const meta = metadata[productId] ?? {}; const design = designs[productId]; const item = design.items.find(x => x.id === design.activeItem) ?? design.items[0]; const colour = product.colours.find((x: any) => x.id === item.colourId) ?? product.colours[0];
  const available = order.filter(v => colour.views[v]); const view = colour.views[design.view] ? design.view : (available[0] as View); const photo = colour.views[view]; const url = assetUrl(photo.assetKey); const area = meta.areas?.[view]; const placement = design.placements[view];
  const setDesign = (fn: (d: Design) => Design) => setDesigns(all => ({ ...all, [productId]: fn(all[productId]) }));
  const patchPlacement = (v: View, next?: Placement) => setDesign(d => { const placements = { ...d.placements }; if (next) placements[v] = next; else delete placements[v]; return { ...d, view: v, placements }; });
  const open = () => { dialog.current?.showModal(); setPanel('home'); };
  const setView = (v: View) => setDesign(d => ({ ...d, view: v }));
  const selectProduct = (id: string) => { setProductId(id); setPanel('home'); setNotice(''); };
  const setColour = async (id: string) => { const variant = product.colours.find((c: any) => c.id === id); if (!variant) return; const target = variant.views[view] ? view : (variant.views.front ? 'front' : order.find(v => variant.views[v])) as View; const source = variant.views[target]; const resolved = source && assetUrl(source.assetKey); if (!resolved) { setNotice('That colour image is unavailable. Your current preview was kept.'); return; } setBusy(true); try { const image = new Image(); image.src = resolved; await image.decode(); setDesign(d => ({ ...d, view: target, items: d.items.map(x => x.id === d.activeItem ? { ...x, colourId: id, sizeId: '' } : x) })); if (target !== view) setNotice(`This colour opens on ${target} because the previous view is unavailable.`); else setNotice(''); } catch { setNotice('The selected colour could not be loaded. Please retry.'); } finally { setBusy(false); } };
  const addDefault = async (v: View) => { if (design.placements[v]) { const before = { ...design.placements }; setUndo(before); patchPlacement(v); return; } const src = sampleLogoUrls.black; if (!src) { setNotice('Missing src/assets/logo-black.png.'); return; } setBusy(true); try { const image = new Image(); image.src = src; await image.decode(); patchPlacement(v, { src, source: 'sample-black', cx: .5, cy: .5, size: .6, angle: 0 }); setUndo(null); } finally { setBusy(false); } };
  const clearAll = () => { setUndo({ ...design.placements }); setDesign(d => ({ ...d, placements: {} })); };
  const replace = async (src: string, source: string) => { if (!placement) return; const image = new Image(); image.src = src; try { await image.decode(); patchPlacement(view, { ...placement, src, source }); setNotice(''); } catch { setNotice('That logo could not be decoded. The existing logo was kept.'); } };
  const upload = (file?: File) => { if (!file) return; if (!['image/png', 'image/jpeg'].includes(file.type) || file.size > 10 * 1024 * 1024) { setNotice('Choose a PNG or JPEG smaller than 10 MB.'); return; } const reader = new FileReader(); reader.onload = () => { const image = new Image(); image.onload = () => image.width * image.height <= 16_000_000 ? void replace(reader.result as string, 'custom') : setNotice('Choose an image below 16 megapixels.'); image.onerror = () => setNotice('That image could not be decoded.'); image.src = reader.result as string; }; reader.readAsDataURL(file); };
  const pointerDown = (e: React.PointerEvent<HTMLImageElement>) => { if (!placement) return; const box = e.currentTarget.parentElement!.getBoundingClientRect(); const centreX = box.left + placement.cx * box.width, centreY = box.top + placement.cy * box.height; drag.current = { view, box, offsetX: e.clientX - centreX, offsetY: e.clientY - centreY }; e.currentTarget.setPointerCapture(e.pointerId); };
  const pointerMove = (e: React.PointerEvent<HTMLImageElement>) => { if (!drag.current || !placement) return; const { box, offsetX, offsetY } = drag.current; const logo = e.currentTarget.getBoundingClientRect(); const halfX = Math.min(.49, logo.width / box.width / 2); const halfY = Math.min(.49, logo.height / box.height / 2); const cx = Math.max(halfX, Math.min(1 - halfX, (e.clientX - offsetX - box.left) / box.width)); const cy = Math.max(halfY, Math.min(1 - halfY, (e.clientY - offsetY - box.top) / box.height)); patchPlacement(view, { ...placement, cx, cy }); };
  const changeItem = (id: number, patch: Partial<Item>) => setDesign(d => ({ ...d, items: d.items.map(x => x.id === id ? { ...x, ...patch } : x) }));
  const total = design.items.reduce((n, x) => n + Math.max(1, x.quantity || 1), 0);
  const downloadCurrentView = async () => { if (!currentSrc || busy) return; const base = new Image(); base.src = currentSrc; await base.decode(); const canvas = document.createElement('canvas'); canvas.width = base.naturalWidth; canvas.height = base.naturalHeight; const context = canvas.getContext('2d')!; context.drawImage(base, 0, 0); if (placement && area) { const logo = new Image(); logo.src = placement.src; await logo.decode(); const safe = area.safeRect; const width = placement.size * safe.width * canvas.width; const height = width * logo.naturalHeight / logo.naturalWidth; const x = (safe.x + placement.cx * safe.width) * canvas.width; const y = (safe.y + placement.cy * safe.height) * canvas.height; context.save(); context.translate(x, y); context.rotate(placement.angle * Math.PI / 180); context.drawImage(logo, -width / 2, -height / 2, width, height); context.restore(); } const link = document.createElement('a'); link.download = `${product.setKey}-${view}-preview.png`; link.href = canvas.toDataURL('image/png'); link.click(); };
  const done = () => { const invalid = design.items.some(x => !x.sizeId || !Number.isInteger(x.quantity) || x.quantity < 1); if (invalid) { setPanel('items'); setNotice('Choose a size and valid quantity for every item.'); return; } const detail = { productId, items: design.items, placements: Object.fromEntries(Object.entries(design.placements).map(([v, p]) => [v, p && { source: p.source, transform: { centreX: p.cx, centreY: p.cy, widthFraction: p.size, rotationDeg: p.angle } }])), specificInstructions: design.notes }; window.dispatchEvent(new CustomEvent('product-customizer:done', { detail })); setNotice('Design details are ready in the product-customizer:done event.'); };
  const activeIndex = available.indexOf(view);
  const currentSrc = url ?? '';
  const swatch = (id: string) => meta.swatches?.[id];
  const guideStyle = (rect: any) => ({ left: `${rect.x * 100}%`, top: `${rect.y * 100}%`, width: `${rect.width * 100}%`, height: `${rect.height * 100}%` });
  const placementStyle = placement ? { left: `${placement.cx * 100}%`, top: `${placement.cy * 100}%`, width: `${placement.size * 100}%`, transform: `translate(-50%,-50%) rotate(${placement.angle}deg)` } : undefined;
  const panelTitle = panel === 'placement' ? 'Logo Placement' : panel === 'items' ? 'Colours and Sizes' : panel === 'notes' ? 'Specific Instructions' : panel === 'products' ? 'Change Product' : '';
  return <><button type="button" onClick={open} className="inline-flex items-center gap-3.5 text-[11px] text-[#c97834]">Discover our materials <span className="text-lg">→</span></button>
    <dialog ref={dialog} className="m-auto h-[min(860px,calc(100dvh-32px))] w-[min(1320px,calc(100vw-32px))] max-h-none max-w-none overflow-hidden border border-[#343434] bg-[#f7f7f7] p-0 text-[#202020] backdrop:bg-[#1d2422]/70 max-[800px]:m-0 max-[800px]:h-dvh max-[800px]:w-screen" aria-label="Product customizer">
      <div className="grid h-full min-h-0 grid-cols-[minmax(0,1fr)_380px] max-[800px]:grid-cols-1 max-[800px]:grid-rows-[46dvh_minmax(0,1fr)]">
        <section className="relative min-h-0 min-w-0 overflow-hidden bg-[#f6f6f6] max-[800px]:row-start-1" aria-label="Product preview">
          <div className="absolute inset-8 bottom-20 flex items-center justify-center max-[800px]:inset-3 max-[800px]:bottom-14">
            <div className="relative max-h-full max-w-full" style={{ aspectRatio: `${photo.width}/${photo.height}`, width: `min(100%, calc((100vh - 150px) * ${photo.width / photo.height}))` }}>
              <img src={currentSrc} alt={`${meta.title ?? product.name}, ${colour.label}, ${view} view`} className="h-full w-full select-none object-contain" draggable={false}/>
              {panel === 'placement' && placement && area && <><div className="pointer-events-none absolute border border-[#444]" style={guideStyle(area.printRect)}/><div className="pointer-events-none absolute border-2 border-dashed border-[#737373]" style={guideStyle(area.safeRect)}><span className="absolute -top-6 left-0 bg-white/90 px-1 text-xs">Safe area</span><img onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={() => drag.current = undefined} src={placement.src} alt="Applied logo" draggable={false} className="absolute max-w-none cursor-move touch-none select-none border-2 border-[#e78335]" style={placementStyle}/></div></>}
            </div>
          </div>
          {available.length > 1 && <><button onClick={() => setView(available[(activeIndex - 1 + available.length) % available.length] as View)} className="absolute left-5 top-1/2 -translate-y-1/2 text-5xl font-light text-black/25" aria-label="Previous view">‹</button><button onClick={() => setView(available[(activeIndex + 1) % available.length] as View)} className="absolute right-5 top-1/2 -translate-y-1/2 text-5xl font-light text-black/25" aria-label="Next view">›</button><div className="absolute bottom-4 left-1/2 flex -translate-x-1/2 gap-3">{available.map(v => <button key={v} onClick={() => setView(v)} aria-label={`${title(v)} view`} className={`h-3 w-3 rounded-full ${v === view ? 'bg-black' : 'bg-black/15'}`}/>)}</div></>}
          <button disabled={busy} onClick={() => void downloadCurrentView()} className="absolute bottom-3 left-4 border border-black/20 bg-white px-3 py-2 text-xs disabled:opacity-40">Download Current View</button>
          {busy && <span className="absolute left-4 top-4 rounded bg-white px-3 py-2 text-sm shadow">Updating preview…</span>}
        </section>
        <aside className="flex min-h-0 flex-col border-l border-black/10 bg-white max-[800px]:row-start-2 max-[800px]:border-l-0 max-[800px]:border-t">
          <header className="flex items-start justify-between border-b-4 border-white bg-[#e5e5e5] px-6 py-5"><div><h2 className="font-display text-[27px] font-semibold leading-[1.05]">{meta.title ?? product.name}</h2><button onClick={() => setPanel('products')} className="mt-2 text-sm text-[#777] underline">Change product</button></div><button onClick={() => dialog.current?.close()} className="p-1 text-sm font-semibold" aria-label="Close customizer">Close ×</button></header>
          {panel === 'home' ? <div className="min-h-0 overflow-y-auto"><button onClick={() => setPanel('placement')} className="flex w-full items-center gap-4 border-b-4 border-white bg-[#f4f4f4] px-6 py-5 text-left"><span className="text-3xl">👕</span><span className="text-base uppercase tracking-wide">Logo Placement</span></button><button onClick={() => setPanel('items')} className="flex w-full items-center gap-4 border-b-4 border-white bg-[#f4f4f4] px-6 py-5 text-left"><span className="text-3xl">🎨</span><span className="text-base uppercase tracking-wide">Colours and Sizes</span><span className="ml-auto rounded border border-black/15 bg-white px-2 py-1 text-xs">List view</span></button><button onClick={() => setPanel('notes')} className="flex w-full items-center gap-4 border-b-4 border-white bg-[#f4f4f4] px-6 py-5 text-left"><span className="text-3xl">✏️</span><span className="text-base uppercase tracking-wide">Specific Instructions</span></button></div> : <><div className="flex items-center gap-3 border-b-4 border-white bg-[#ededed] px-5 py-4"><button onClick={() => setPanel('home')} aria-label="Back">←</button><h3 className="text-base uppercase tracking-wide">{panelTitle}</h3></div><div className="min-h-0 flex-1 overflow-y-auto p-6">
            {panel === 'placement' && <><ul className="ml-5 list-disc text-sm leading-6"><li>Select your placement(s) below.</li><li>Tap again if you want to remove.</li><li>Choose Blank for no logo.</li></ul><div className="mt-5 grid grid-cols-3 gap-4 text-center"><button onClick={clearAll} className={`text-xs ${Object.keys(design.placements).length ? '' : 'font-bold'}`}><span className="mx-auto mb-2 grid h-14 w-14 place-items-center rounded-full border-2 border-[#888] bg-[#222] text-white">—</span>BLANK</button>{available.filter(v => meta.areas?.[v]).map(v => <button key={v} onClick={() => void addDefault(v)} className={`text-xs ${design.placements[v] ? 'font-bold text-[#c97834]' : ''}`}><span className={`mx-auto mb-2 block h-14 w-14 overflow-hidden rounded-full border-2 ${design.placements[v] ? 'border-[#c97834]' : 'border-[#888]'}`}><img src={assetUrl(colour.views[v].assetKey)} className="h-full w-full object-cover" alt=""/></span>{title(v).toUpperCase()}</button>)}</div>{undo && <button onClick={() => { setDesign(d => ({ ...d, placements: undo })); setUndo(null); }} className="mt-4 text-sm underline">Undo removal</button>}{placement && <div className="mt-7 border-t pt-5"><p className="font-semibold">Edit {title(view)}</p><div className="mt-3 grid grid-cols-3 gap-2"><button onClick={() => void replace(sampleLogoUrls.white!, 'sample-white')} className="rounded border bg-[linear-gradient(45deg,#ddd_25%,transparent_25%),linear-gradient(-45deg,#ddd_25%,transparent_25%)] p-2 text-xs">White</button><button onClick={() => void replace(sampleLogoUrls.black!, 'sample-black')} className="rounded border p-2 text-xs">Black</button><label className="cursor-pointer rounded border p-2 text-center text-xs">Upload<input type="file" accept="image/png,image/jpeg" className="sr-only" onChange={e => upload(e.target.files?.[0])}/></label></div><label className="mt-4 block text-sm">Size<input type="range" min=".15" max=".9" step=".01" value={placement.size} onChange={e => patchPlacement(view, { ...placement, size: +e.target.value })} className="mt-2 w-full accent-[#e78335]"/></label><label className="mt-4 block text-sm">Rotation<input type="range" min="-180" max="180" value={placement.angle} onChange={e => patchPlacement(view, { ...placement, angle: +e.target.value })} className="mt-2 w-full accent-[#e78335]"/></label><button onClick={() => patchPlacement(view, { ...placement, cx: .5, cy: .5 })} className="mt-3 text-sm underline">Centre</button></div>}</>}
            {panel === 'items' && <><p className="text-sm text-[#666]">All item rows share the same logo design and notes.</p>{design.items.map((row, index) => <div key={row.id} className={`mt-4 border ${row.id === design.activeItem ? 'border-[#e78335]' : 'border-black/10'}`}><button onClick={() => setDesign(d => ({ ...d, activeItem: row.id }))} className="flex w-full justify-between bg-[#f4f4f4] p-3 text-sm"><span>{index + 1} &nbsp; Item {index + 1}</span><span>×{row.quantity}</span></button><div className="p-4"><p className="text-sm font-semibold">ITEM COLOUR</p><div className="mt-3 grid grid-cols-4 gap-3">{product.colours.map((c: any) => <button key={c.id} onClick={() => { setDesign(d => ({ ...d, activeItem: row.id, view: c.views?.[d.view] ? d.view : ((c.views?.front ? 'front' : order.find(v => c.views?.[v])) as View), items: d.items.map(x => x.id === row.id ? { ...x, colourId: c.id, sizeId: '' } : x) })); }} className="text-[11px]"><span className={`mx-auto mb-1 block h-11 w-11 rounded-full border-[3px] ${row.colourId === c.id ? 'border-[#e78335]' : 'border-[#888]'}`} style={{ backgroundColor: swatch(c.id) ?? '#ddd' }}/>{c.label.toUpperCase()}</button>)}</div><label className="mt-5 block text-sm font-semibold">SIZE<select value={row.sizeId} onChange={e => changeItem(row.id, { sizeId: e.target.value })} className="mt-2 w-full rounded border border-[#888] bg-white p-3"><option value="">Choose your size</option>{(meta.sizes ?? []).map((s: string) => <option key={s}>{s}</option>)}</select></label><label className="mt-4 block text-sm font-semibold">QUANTITY<input type="number" min="1" step="1" value={row.quantity} onChange={e => changeItem(row.id, { quantity: Math.max(1, Math.floor(+e.target.value || 1)) })} className="mt-2 w-full rounded border border-[#888] p-3"/></label>{design.items.length > 1 && <button onClick={() => setDesign(d => ({ ...d, items: d.items.filter(x => x.id !== row.id), activeItem: d.items[0].id }))} className="mt-3 text-xs underline">Remove item</button>}</div></div>)}<button onClick={() => { const id = nextItem.current++; setDesign(d => ({ ...d, activeItem: id, items: [...d.items, { id, colourId: item.colourId, sizeId: '', quantity: 1 }] })); }} className="mt-4 w-full border border-[#333] p-3 text-sm font-semibold">Add Another Item</button><p className="mt-3 text-right text-sm">Total quantity: {total}</p></>}
            {panel === 'notes' && <><label className="block text-sm font-semibold">Special notes or requirements<textarea value={design.notes} maxLength={1000} onChange={e => setDesign(d => ({ ...d, notes: e.target.value }))} placeholder="Add any notes about your logo, placement, or special requirements." className="mt-3 h-36 w-full rounded border border-[#999] p-3 font-normal"/></label><p className="mt-1 text-right text-xs text-[#777]">{design.notes.length}/1000</p><p className="mt-4 text-sm text-[#666]">Notes apply to this product design and are not submitted automatically.</p></>}
            {panel === 'products' && <div className="grid grid-cols-2 gap-3">{products.map(p => <button key={p.id} onClick={() => selectProduct(p.id)} className={`rounded border p-3 text-left text-sm ${p.id === productId ? 'border-2 border-[#e78335]' : 'border-black/15'}`}><span className="text-xs uppercase text-[#777]">{p.category}</span><strong className="mt-1 block">{metadata[p.id]?.title ?? p.name}</strong></button>)}</div>}
          </div><footer className="flex gap-2 border-t border-black/10 p-4"><button onClick={() => setPanel('home')} className="flex-1 border border-[#333] p-3 text-sm">Back</button><button onClick={done} className="flex-1 bg-[#252525] p-3 text-sm text-white">Done</button></footer></>}
          {notice && <p className="border-t border-amber-200 bg-amber-50 px-4 py-2 text-xs text-amber-900">{notice}</p>}
        </aside>
      </div>
    </dialog></>;
}
